Question
smartblog/qna pull request #1
Opened 2017-05-31 15:32 UTC by smartblog

2017-05-31 18:08 UTC, iBublik requested changes

2017-05-31 18:08 UTC, iBublik commented on app/models/question.rb
> +  has_many :answers
Нужно обработать удаление вопроса - что будет с прикрепленными ответами?

2017-05-31 18:08 UTC, iBublik commented on app/models/question.rb
> +  has_many :answers
Не забудь на это тест написать (есть в shoulda-mathcers)

2017-05-31 18:08 UTC, iBublik commented on db/migrate/20170531151931_add_answers_to_question.rb
> +    add_belongs_to :answers, :question, index: true
Стоит внешний ключ добавить

2017-05-31 18:08 UTC, iBublik commented on spec/factories/answers.rb
> +    body "MyText"
Не хватает связи с вопросом - а без этого фабрика нерабочая (в Rails 5 связи по умолчанию обязательные)

2017-05-31 18:08 UTC, iBublik commented on spec/models/answer_spec.rb
> +  it { should belong_to(:question) }
Придерживайся одного стиля - либо пиши скобки, либо нет

2017-06-01 16:24 UTC, iBublik commented on spec/factories/answers.rb
> +    body "MyText"
Это замечание актуально. Попробуй создать ответ фабрикой (`create :answer`)

2017-06-01 16:39 UTC, smartblog commented on spec/factories/answers.rb
> +    body "MyText"
Прошу прощения, но не могу понять, видимо после рабочего дня голова уже не варит
В скринкасте про фабрику ничего не нашел
Подтолкните ссылочкой плиз

2017-06-01 16:45 UTC, iBublik commented on spec/factories/answers.rb
> +    body "MyText"
Смотри, в 5 рельсах ассоциации `belongs_to` по умолчанию являются обязательными. То есть создать ответ без вопроса не получится - будет ошибка валидации. Фабрики по умолчанию должны быть валидными. Т.е. в эту фабрику нужно добавить создание вопроса. Как это сделать можно посмотреть [тут](https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#associations)

2017-06-01 16:54 UTC, vkurennov approved these changes

2017-06-01 16:54 UTC, vkurennov commented on spec/factories/answers.rb
> +    body "MyText"
В целом, пока это не критично, станет критично в следующем уроке, тогда и можно будет поправить

2017-06-01 16:54 UTC, vkurennov commented on spec/models/answer_spec.rb
> +  it { should belong_to :question }
В моделях мы пишем сначала ассоциации, потом - валидации. Придерживайся в тестах того же порядка

2017-06-08 13:47 UTC, merged