Lesson26
smartblog/qna pull request #3
Opened 2017-06-23 14:15 UTC by smartblog

2017-06-23 16:12 UTC, iBublik requested changes

2017-06-23 16:12 UTC, iBublik commented on app/controllers/questions_controller.rb
> +    if current_user.author?(@question)
Довольно громоздкая лестница условий получилась. Можно для update и destroy добавить before_action, в котором будет происходит редирект если пользователь не является автором

2017-06-23 16:12 UTC, iBublik commented on app/models/user.rb
> +  def author?(content)
Я бы назвал параметр `resource`

2017-06-23 16:12 UTC, iBublik commented on app/views/questions/_form.html.slim
> +    = f.label :user_id, :class => 'control-label col-lg-2'
А это зачем?

2017-06-23 16:12 UTC, iBublik commented on app/views/questions/_form.html.slim
> +    = f.label :user_id, :class => 'control-label col-lg-2'
Вообще я не обнаружил где эта форма используется

2017-06-23 16:12 UTC, iBublik commented on config/routes.rb
>      resources :answers, shallow: true
Оставь тут только те роуты, которые реально используются

2017-06-23 16:12 UTC, iBublik commented on spec/acceptance/create_answer_spec.rb
> +feature 'Create answer', %q{
Не хватает теста с попыткой создания невалидного ответа. Проверить нужно именно наличие ошибок валидации на странице

2017-06-23 16:12 UTC, iBublik commented on spec/acceptance/create_answer_spec.rb
> +    expect(page).to_not have_content 'Create answer'
Для отрицания в приемочных тестах лучше использовать капибаровские матчеры - `to have_no_content` вместо `to_not have_content`. В них встроено ожидание, так что если элемент есть на странице, тест не упадет, а будет периодически проверять не пропал ли он (пока время ожидания не превысит максимально установленное). Это очень удобно на страницах где есть js (будет далее по курсу), так что привыкай к хорошему сразу :)

2017-06-23 16:12 UTC, iBublik commented on spec/acceptance/create_question_spec.rb
> +feature 'Create question', %q{
Тут так же не хватает теста на создание невалидного вопроса

2017-06-23 16:12 UTC, iBublik commented on spec/models/user_spec.rb
> +RSpec.describe User do
Не хватает теста на метод `author?`

2017-06-23 16:12 UTC, iBublik commented on spec/acceptance/delete_answer_spec.rb
> +  given(:answer) { create(:answer) }
Этот хелпер нигде не используется, ответ никогда не создастся. Можно убрать.

2017-06-23 16:12 UTC, iBublik commented on spec/acceptance/delete_question_spec.rb
> +  given(:question) { create(:question) }
Аналогично, хелпер бесполезен

2017-06-23 16:12 UTC, iBublik commented on spec/acceptance/list_questions_spec.rb
> +    expect(page).to have_content questions.first.title
Можно в цикле проверять

2017-06-23 16:12 UTC, iBublik commented on spec/factories/answers.rb
> +  sequence :body do |n|
Такие последовательности лучше объявлять внутри фабрик, чтоб они не засоряли глобельно пространство. Вне фабрик объявляются только переиспользуемые последовательности, и обычно их помещают в отдельный файл (sequences.rb, например)

2017-06-23 16:12 UTC, iBublik commented on spec/factories/questions.rb
> +  sequence :title do |n|
См. мой коммент по поводу последоватльности `body`

2017-06-23 16:12 UTC, iBublik commented on spec/acceptance/view_question_spec.rb
> +  scenario 'Unauthenticated user view the question and their answers' do
А где же список ответов в этом тесте? :)

2017-06-24 05:28 UTC, smartblog commented on app/models/user.rb
> +  def author?(content)
Согласен, так понятней

2017-06-24 05:29 UTC, smartblog commented on app/views/questions/_form.html.slim
> +    = f.label :user_id, :class => 'control-label col-lg-2'
С формой я погорячился, экспериментировал с bootstrap:theme и наделал делов

2017-06-24 05:32 UTC, smartblog commented on config/routes.rb
>      resources :answers, shallow: true
Здесь немного не понял, вроде они все используются
Или devise_for :users необязателен? Без него будут работать всякие sign_in и т.п.?

2017-06-24 05:37 UTC, smartblog commented on spec/acceptance/create_answer_spec.rb
> +feature 'Create answer', %q{
Подскажите, валидация же происходит на уровне модели, или ее нужно дублировать и в acceptance тестах? Не получится ли тогда тавталогия в тестах?

2017-06-24 06:00 UTC, smartblog commented on spec/acceptance/create_answer_spec.rb
> +    expect(page).to_not have_content 'Create answer'
Поправил

2017-06-24 06:01 UTC, smartblog commented on spec/acceptance/create_answer_spec.rb
> +feature 'Create answer', %q{
Дошло до меня, ведь пользователь должен увидеть ошибку или предупреждение. Сделал

2017-06-24 06:03 UTC, smartblog commented on spec/acceptance/create_question_spec.rb
> +feature 'Create question', %q{
Понял, добавил

2017-06-24 06:13 UTC, smartblog commented on spec/models/user_spec.rb
> +RSpec.describe User do
Добавил и для вопросов и для ответов

2017-06-24 06:18 UTC, smartblog commented on spec/acceptance/delete_answer_spec.rb
> +  given(:answer) { create(:answer) }
Понял. удалил

2017-06-24 06:18 UTC, smartblog commented on spec/acceptance/delete_question_spec.rb
> +  given(:question) { create(:question) }
удалил

2017-06-24 06:24 UTC, smartblog commented on spec/acceptance/view_question_spec.rb
> +  scenario 'Unauthenticated user view the question and their answers' do
=))) Затупил и забыл

2017-06-24 06:25 UTC, smartblog commented on spec/factories/questions.rb
> +  sequence :title do |n|
Перемещаю внутрь и у меня ломается =( Буду читать

2017-06-24 06:41 UTC, iBublik commented on config/routes.rb
>      resources :answers, shallow: true
Я только про `resources :answers`. В контроллере всего 2 экшена сейчас, а в роутах полный набор

2017-06-24 06:42 UTC, iBublik commented on spec/factories/questions.rb
> +  sequence :title do |n|
А что ломается-то? Вот так должно работать:
```ruby
factory :question do
  sequence(:title) { |n| "MyString#{n}" }
  body 'MyText'
  user
end
```

2017-06-24 06:43 UTC, iBublik commented on spec/models/user_spec.rb
> +RSpec.describe User do
Да можно было для одного ресурса

2017-06-24 06:54 UTC, iBublik commented on app/controllers/questions_controller.rb
> +    if current_user.author?(@question)
Это рекомендация, но игнорировать не стоит

2017-06-24 06:54 UTC, iBublik commented on app/views/questions/show.html.slim
> +- if current_user && current_user.author?(@question)
В Ruby 2.3+ есть safe navigation operator - `current_user&.author?(@question)`. Он позволяет избежать проверки на nil

2017-06-24 06:54 UTC, iBublik commented on spec/acceptance/list_questions_spec.rb
> +    expect(page).to have_content questions.first.title
Опять же рекомендация, но лучше к ней прислушаться. У тебя сейчас тест завязан на проверке всего 2 вопросов. Но список может и больше содержать, цикл в этом плане универсален

2017-06-24 06:54 UTC, iBublik commented on spec/models/user_spec.rb
> +  describe 'check author? for questions' do
Инстанс методы описываются так `describe #author?` do ...`

2017-06-24 07:02 UTC, iBublik requested changes

2017-06-24 07:02 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
>    describe 'POST #create' do
А где же тесты на destroy? Должно быть как в контроллере вопросов - для автора и не автора

2017-06-24 07:20 UTC, smartblog commented on spec/acceptance/list_questions_spec.rb
> +    expect(page).to have_content questions.first.title
Сорри, как-то пропустил эту рекомендацию. Сделал как надо

2017-06-24 07:25 UTC, smartblog commented on spec/factories/questions.rb
> +  sequence :title do |n|
У меня была очепятка =))) Спасибо

2017-06-24 07:30 UTC, smartblog commented on spec/controllers/answers_controller_spec.rb
>    describe 'POST #create' do
Блин =)) проморгал
Добавил

2017-06-24 09:39 UTC, vkurennov requested changes

2017-06-24 09:39 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if current_user.author?(@question)
Да, стоит прислушаться к этой рекомендации

2017-06-24 09:39 UTC, vkurennov commented on app/views/answers/show.html.slim
> +p= @answer.body
у нас нет отдельного вида для ответа. нужно удалить его

2017-06-24 09:39 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +    expect(page).to have_content 'Your question successfully created.'
Тут надо проверить, что на странице есть текст и тело созданного вопроса

2017-06-24 09:39 UTC, vkurennov commented on spec/acceptance/delete_answer_spec.rb
> +    expect(page).to have_content 'Your answer successfully destroy'
Надо еще проверить, что ответа больше нет на странице

2017-06-24 09:39 UTC, vkurennov commented on spec/acceptance/delete_answer_spec.rb
> +  scenario 'User try delete not his answer' do
еще нужен аналогичный сценарий для незалогиненного юзера

2017-06-24 09:39 UTC, vkurennov commented on spec/acceptance/delete_question_spec.rb
> +    expect(page).to have_content 'Your question successfully destroy'
Надо проврить, что вопроса больше нет на странице

2017-06-24 09:39 UTC, vkurennov commented on spec/acceptance/delete_question_spec.rb
> +  scenario 'User try delete not his question' do
И аналогичный сценарий для незалогиненного юзера

2017-06-24 09:39 UTC, vkurennov commented on spec/models/user_spec.rb
> +  describe '#author? for questions' do
Нет смысла проверять на каждый тип аргумента, у тебя же универсальный метод. Ты впоследсвтии его можешь использовать и с комментариями и еще с чем угодно, но это не значит, что надо с каждым возможным типом тестировать

2017-06-25 13:17 UTC, smartblog commented on app/controllers/questions_controller.rb
> +    if current_user.author?(@question)
Артем, прошу прощения, я не знаю как дважды пропустил это замечание. =)) Видимо просто поторопился
Надеюсь понял все правильно и сделал верно.

2017-06-25 13:29 UTC, smartblog commented on app/views/answers/show.html.slim
> +p= @answer.body
удалил

2017-06-25 13:29 UTC, smartblog commented on spec/acceptance/create_question_spec.rb
> +    expect(page).to have_content 'Your question successfully created.'
сделал

2017-06-25 13:30 UTC, smartblog commented on spec/acceptance/delete_answer_spec.rb
> +    expect(page).to have_content 'Your answer successfully destroy'
Сделал, надеюсь я реализовал это не очень отстойно =)

2017-06-25 13:31 UTC, smartblog commented on spec/acceptance/delete_answer_spec.rb
> +  scenario 'User try delete not his answer' do
Неподумал =) сделал

2017-06-25 18:08 UTC, iBublik commented on spec/acceptance/create_question_spec.rb
> +    expect(page).to have_content 'Your question successfully created.'
Только тело проверяется, заголовок тоже не мешает проверить

2017-06-25 18:08 UTC, iBublik commented on spec/acceptance/delete_answer_spec.rb
> +    @temp_body = user_with_answers.answers.first.body
Инстанс переменные в тестах не используются практически никогда. В данном случае спокойно можно использовать локальную. А еще лучше вынести в хелпер `given(:answer) { user_with_answers.first }` и дальше работать с ней - `visit question_path(answer.question)`, `expect(page).to have_no_content answer.body`

2017-06-25 18:08 UTC, iBublik commented on spec/acceptance/delete_question_spec.rb
> +    @temp_title = user_with_questions.questions.first.title
См. мой коммент про удаление ответа

2017-06-25 18:08 UTC, iBublik commented on spec/models/user_spec.rb
> +  let(:user_with_answers) { create(:user_with_answers) }
Этот хелпер больше не используется

2017-06-25 18:08 UTC, iBublik commented on spec/models/user_spec.rb
> +  describe '#author? for questions' do
Инстанс методы описываются просто `describe '#author?'`, т.е. в кавычках лишь название метода. Все остальное описание идет в контекстах или самих тестах. В данном случае `for questions` вообще избыточно

2017-06-25 18:08 UTC, iBublik commented on spec/models/user_spec.rb
> +      expect(user_with_questions).to be_author(user_with_questions.questions.first)
Как-то это громоздко выглядит. Порой лучше в хелперах чуть больше работы сделать:
```ruby
let(:user) { create :user }
let(:question) { create :question }
let(:author) { question.user }
...

expect(author).to be_author(question)
...
expect(user).to_not be_author(question)
```

2017-06-28 06:31 UTC, smartblog commented on spec/models/user_spec.rb
> +      expect(user_with_questions).to be_author(user_with_questions.questions.first)
Вау, так намного круче, спасибо

2017-06-28 06:31 UTC, smartblog commented on spec/models/user_spec.rb
> +  describe '#author? for questions' do
Понял, исправлю

2017-06-28 06:32 UTC, smartblog commented on spec/acceptance/delete_answer_spec.rb
> +    @temp_body = user_with_answers.answers.first.body
Позорище мне, настрочил кака-кода =) Пока еще мой мозг кривовато работает, спасибо за советы

2017-06-28 06:34 UTC, merged