Lesson27
smartblog/qna pull request #4
Opened 2017-06-28 12:55 UTC by smartblog

2017-06-28 16:49 UTC, iBublik requested changes

2017-06-28 16:49 UTC, iBublik commented on app/views/answers/create.js.erb
> +$('.answers').html('<%= j render 'questions/answers' %>');
В задании специально выделено жирным:
> нужно добавлять только вновь созданный ответ к вопросу, без повторного рендеринга всего списка ответов

2017-06-28 16:49 UTC, iBublik commented on app/views/questions/_answers.html.slim
> +- @question.answers.each do |answer|
Лучше создай партиал для одного ответа, тогда можно будет делать `render @question.answers`
И в целом хорошей практикой считается явная передача параметров в партиалы. Они создаются переиспользования, поэтому завязываться на глобальный контекст (инстанс переменные во вьюхах) плохо. Даже рельсы когда ты пишешь `render @question.answers` преобразуют это в 
```ruby
- @question.answers.each do |answer|
  = `render 'answers/answer', answer: answer
```
Заметь, там передается переменная в партиал

2017-06-28 17:33 UTC, smartblog commented on app/views/answers/create.js.erb
> +$('.answers').html('<%= j render 'questions/answers' %>');
В скринкасте был специально создан partial в question и меня это немного сбило
Переделал, надеюсь правильно понял

2017-06-28 18:18 UTC, iBublik commented on app/controllers/answers_controller.rb
> +    @answer = @question.answers.create(answer_params)
А зачем тут create, а ниже save?

2017-06-28 18:30 UTC, smartblog commented on app/controllers/answers_controller.rb
> +    @answer = @question.answers.create(answer_params)
А я же делаю @answer.user = current_user
Или только в консоли делаем save?

2017-06-28 18:39 UTC, iBublik commented on app/controllers/answers_controller.rb
> +    @answer = @question.answers.create(answer_params)
Не понял вопроса.
Ты перед тем как юзера привязать пытаешься запись сохранить в базу. Но из-за валидации (без юзера не пропустит) сохранения не происходит, зато ниже при вызове `@answer.save` сохраняется. Собственно вопрос зачем пытаться сохранить заведомо невалидную запись?

2017-06-28 18:53 UTC, smartblog commented on app/controllers/answers_controller.rb
> +    @answer = @question.answers.create(answer_params)
Сорри, загруз на работе весьма негативно сказывается на моем обучении =)
Теперь вроде дошло, исправлю

2017-06-28 19:09 UTC, vkurennov requested changes

2017-06-28 19:09 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer = @question.answers.create(answer_params)
Верно, используй new

2017-06-28 19:09 UTC, vkurennov commented on app/views/answers/create.js.erb
> +$('.answers').html('<%= j render @answer %>');
Ты заменяешь весь список ответов одним ответом, а надо добавлять, у тебя же в этом случае все предыдущие ответы на странице пропадут

2017-06-28 19:18 UTC, smartblog commented on app/views/answers/create.js.erb
> +$('.answers').html('<%= j render @answer %>');
Я немного запутался,
нужно` render @question.answers` ?

2017-06-28 19:26 UTC, smartblog commented on app/views/answers/create.js.erb
> +$('.answers').html('<%= j render @answer %>');
Нет, так вообще js не отрабатывает

2017-06-28 19:26 UTC, iBublik commented on app/views/answers/create.js.erb
> +$('.answers').html('<%= j render @answer %>');
Нет, у тебя есть список ответов, новый нужно добавить к ним. А сейчас у тебя новый ответ заменяет все остальные. Тебе просто нужен правильный метод из jQuery

2017-06-28 19:29 UTC, smartblog commented on app/views/answers/create.js.erb
> +$('.answers').html('<%= j render @answer %>');
Вроде дошло, сейчас добью

2017-06-28 19:31 UTC, smartblog commented on app/views/answers/create.js.erb
> +$('.answers').html('<%= j render @answer %>');
Немного вы меня опередили, я почти сам допер что дело в методе jquery, а то как баран смотрел в одно место

2017-06-29 08:30 UTC, vkurennov approved these changes

2017-06-29 10:10 UTC, merged